### ISSUE TITLE
ES7 exponentiation issue

### ISSUE THREAD

**Issue by CyborgDroid** [hiyan/gekkowk#2]
I'm getting the following error when running the file from the console and from the UI:

/Users/macbook/Sites/gekko-nn/strategies/indicators/BB.js:30
    this.sumsq += this.diffs[this.age] ** 2  - diffsTail ** 2;
                                        ^
SyntaxError: Unexpected token *

It seems that the exponentiation operator was added by ECMAScript 2016 (ES7). I am replacing it with Math.pow() as a workaround. 
```
//this.sumsq += this.diffs[this.age] ** 2  - diffsTail ** 2;
this.sumsq += Math.pow(this.diffs[this.age], 2)  - Math.pow(diffsTail, 2);
```

**Comment by hiyan** [comment]
The indicator was copied from https://github.com/atselevich

As I'm not using it, you may want to inform atselevich on your issue.
